### ISSUE TITLE
UK academic outreach

### ISSUE THREAD

**Issue by jamiehowarth0** [dotnet-foundation/wg-outreach#2]
For the next meeting, I'd like to get involved with UK K-12 outreach. I've signed up as a tutor for [Code First: Girls](https://www.codefirstgirls.org.uk/) & I'm reaching out to high schools in the south-west of England to start trying to work with them to develop code clubs.

**Comment by SaraJo** [comment]
That sounds great! Scheduling the next meeting now. Will add to the agenda if you are able to make it?

**Comment by benjaminhowarth1** [comment]
I'd love to, yes please 🙂

**Comment by benjaminhowarth1** [comment]
Update: I have a call next Tuesday with someone at CF:G to discuss developing an "Introduction to .NET Programming" course.

**Comment by benjaminhowarth1** [comment]
Further update: CF:G would love to explore developing two curricula for their courses - one on C# for sure, and one maybe on ASP.NET.
Due to COVID-19 issues, we'd also like somebody from MS to help with access to Teams to enable virtual learning.
@vnwonah would also like to help develop the C# curriculum for use outside the CF:G & UK.

**Comment by SaraJo** [comment]
Great. I just added a format for proposals and a sample proposal (feedback welcomed). Want to be our first proposal submitted?

**Comment by shawnwildermuth** [comment]
Closed as complete.
