### ISSUE TITLE
Send Meetup list to Jayme

### ISSUE THREAD

**Issue by jguadagno** [dotnet-foundation/wg-outreach#85]
Send the meetup list to Jayme Singleton to compare with the Azure sponsored meetup list.

**Comment by nicoleabuhakmeh** [comment]
I have compared the lists and sent it over to our contact at Meetup.  I have asked our contact to remove the double billed groups from our account.  I will ask them to resend the invoice (due in July) with the corrected number of pro accounts to reduce our bill for the 20 double billed groups.

**Comment by nicoleabuhakmeh** [comment]
Meetup Replied: 

The groups listed are not actually double billed although it may appear that way. The groups are a part of both the [DotNet pro network](https://www.meetup.com/pro/dotnet/) and the [Azure Tech pro network](https://www.meetup.com/pro/azuretechgroups/) on Meetup. The DotNet Foundation has a paid subscription for their pro network to support and have a relationship with these groups and Microsoft has their own paid subscription for their separate pro network to support and have their own relationship with them. So, each organization has their own relationship with the group, separately, so that each can interact and communicate with the group via the pro dashboard tools, etc. 

For example, the Sri Lanka Developer Forum group  is a part of your [DotNet pro network](https://www.meetup.com/pro/dotnet/), but it's just not displayed and supported as being so on the group page, but DotNet still receives all the benefits of being able to access and connect with the group because it is part of the network. The group is also a part of the [Azure Tech pro network](https://www.meetup.com/pro/azuretechgroups/), so Microsoft has their own relationship with the group. The benefit here for the group is that they are able to have a relationship with Azure and a relationship with DotNet. The first network a group joins is the one that will be displayed on the group page itself, which is why you don't see that the group is also actually a part of the DotNet pro network. And for example, the [.NET São Paulo](https://www.meetup.com/dotnet-Sao-Paulo/) is also a part of both the DotNet pro network and Azure Tech pro network, but it displays as part of the DotNet pro network because it was the first network the group joined, but they are still able to have a separate relationship with both organizations.

@jguadagno I think i'm going to go ahead and ask Meetup to remove those 20 groups. Their explanation doesn't quite cop to the fact that the groups are being counted and in turn being paid for by both of DNF and Azure. The groups will still be covered by the Azure group for the features they use under Meetup.  Thoughts?

**Comment by jguadagno** [comment]
Sounds like Meetup has come up with a fancy way to cover the double billing.  Since our Meetup relationship is just to pay the bills, I am fine with remove the duplications from the Foundation list @nicoleabuhakmeh

**Comment by nicoleabuhakmeh** [comment]
I have moved forward with asking Meetup to remove those 20 groups.
